behaviors:
<<<<<<< HEAD
<<<<<<< HEAD
  ObstacleCourse:
=======
  BigWallJump:
>>>>>>> f4debb3 (Updated a Obstacle Course)
=======
  ObstacleCourse:
>>>>>>> 1df63e2 (Final Changes)
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
<<<<<<< HEAD
<<<<<<< HEAD
    max_steps: 500000
    time_horizon: 128
    summary_freq: 50000
    threaded: true
  ObstacleCourseHard:
=======
    max_steps: 20000000
=======
    max_steps: 500000
>>>>>>> 1df63e2 (Final Changes)
    time_horizon: 128
    summary_freq: 50000
    threaded: true
<<<<<<< HEAD
  SmallWallJump:
>>>>>>> f4debb3 (Updated a Obstacle Course)
=======
  ObstacleCourseHard:
>>>>>>> 1df63e2 (Final Changes)
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
<<<<<<< HEAD
<<<<<<< HEAD
    max_steps: 500000
    time_horizon: 128
    summary_freq: 50000
=======
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 20000
>>>>>>> f4debb3 (Updated a Obstacle Course)
=======
    max_steps: 500000
    time_horizon: 128
    summary_freq: 50000
>>>>>>> 1df63e2 (Final Changes)
    threaded: true
